lib: fix build issue when building for non-RCAR platform
Use old value for TEE_SCN_MAX (70) instead of 73 for non-RCAR
platforms in order to be in sync with the number of syscall entries
in tee_svc_syscall_table.

Build error without the fix:

In file included from core/arch/arm/tee/arch_svc.c:29:0:
core/arch/arm/tee/arch_svc.c: In function ‘tee_svc_handler’:
lib/libutils/isoc/include/assert.h:52:24: error: duplicate case value
   switch (0) { case 0: case ((x) ? 1: 0): default : break; } \
                        ^
core/arch/arm/tee/arch_svc.c:215:2: note: in expansion of macro
‘COMPILE_TIME_ASSERT’
  COMPILE_TIME_ASSERT(ARRAY_SIZE(tee_svc_syscall_table) ==
  ^~~~~~~~~~~~~~~~~~~
lib/libutils/isoc/include/assert.h:52:16: error: previously used here
   switch (0) { case 0: case ((x) ? 1: 0): default : break; } \
                ^
core/arch/arm/tee/arch_svc.c:215:2: note: in expansion of macro
‘COMPILE_TIME_ASSERT’
  COMPILE_TIME_ASSERT(ARRAY_SIZE(tee_svc_syscall_table) ==
  ^~~~~~~~~~~~~~~~~~~
mk/compile.mk:146: recipe for target
'out/arm-plat-zynqmp/core/arch/arm/tee/arch_svc.o' failed
make: *** [out/arm-plat-zynqmp/core/arch/arm/tee/arch_svc.o] Error 1

Signed-off-by: Stefan Sicleru <stefan_sicleru@mentor.com>
Signed-off-by: Yoshifumi Hosoya <yoshifumi.hosoya.wj@renesas.com>